# Site settings
title: Erickmob LTDA
email: erickmobltda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Erickmob LTDA is a company that provides software engineering services any company worldwide. Contact us to get more info about our portifolio, services and values.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: moica77
github_username:  erickmob

# Build settings
markdown: kramdown
